feat: op rebate rewards
across-protocol/scraper-api pull request #286
Opened 2023-11-20 11:14 UTC by dohaki

Closes ACX-1654

This PR implements OP rebate rewards as a new entity. The idea is that the `src/modules/rewards/model/reward.entity.ts` can be used in the future to also present other types of rewards that are tied to a deposit. The PR therefore also adds a new module `src/modules/rewards/module.ts` and controller `src/modules/rewards/entrypoints/http/controller.ts` that serve as an entrypoint for future reward programs.

2023-11-22 13:24 UTC, amateima requested changes
This looks very good, but I have one suggestion. I don't feel comfortable with having a single `reward` table because we don't know the requirements of the future rewards. I can give you two examples of restrictions that may not apply to future reward types:
1. `reward` table limits the deposits to having a single reward type per recipient. This may not be true for other reward types
2. `reward` table has a `rewardTokenPriceId` column assuming that all the rewards computations will involve a token price which may not be necessary for other rewards.

Considering this I propose to have dedicated tables for each reward type, so we can be very flexible with the rules and the columns for each reward type. Wdyt?

2023-11-22 14:14 UTC, dohaki commented
@amateima Thanks for the review! I wanted to provide my thoughts first regarding your input on single VS. multiple reward tables before I dive into the single review comments.

> 1. reward table limits the deposits to having a single reward type per recipient. This may not be true for other reward types

We use the `@ManyToOne(() => Deposit)` decorator in the reward entity. So a reward can have a single deposit but a deposit can have many rewards. Or maybe you are referring to this constraint
```
@Unique("UK_reward_recipient_type_depositPk", ["recipient", "type", "depositPrimaryKey"])
```
? This constraint limits that a specific reward type can only be associated with a single deposit per user. But yea, this would prevent the creation of multiple rewards of the same type for the same deposit and user. 

 > 2. reward table has a rewardTokenPriceId column assuming that all the rewards computations will involve a token price which may not be necessary for other rewards.

I just had a look and actually this one is not needed 😅 So this could be removed from the entity.

So some other arguments I had in mind for having a single table are:
- Single consistent interface for querying all types of rewards
- Ability to populate rewards in deposits with a single JOIN
  - If we, for example, had the `referrals` rewards also in this table, then we could have added a new column to the `deposits` entity to populate all related rewards with a single JOIN. 

But I also get your point of having multiple tables. Because all above arguments could be achieved with multiple tables. And because the referrals are always in a separate view/table, we would need to some stitching anyways 🤔

2023-11-22 14:24 UTC, amateima commented
> @amateima Thanks for the review! I wanted to provide my thoughts first regarding your input on single VS. multiple reward tables before I dive into the single review comments.
> 
> > 1. reward table limits the deposits to having a single reward type per recipient. This may not be true for other reward types
> 
> We use the `@ManyToOne(() => Deposit)` decorator in the reward entity. So a reward can have a single deposit but a deposit can have many rewards. Or maybe you are referring to this constraint
> 
> ```
> @Unique("UK_reward_recipient_type_depositPk", ["recipient", "type", "depositPrimaryKey"])
> ```
> 
> ? This constraint limits that a specific reward type can only be associated with a single deposit per user. But yea, this would prevent the creation of multiple rewards of the same type for the same deposit and user.
> 
> > 2. reward table has a rewardTokenPriceId column assuming that all the rewards computations will involve a token price which may not be necessary for other rewards.
> 
> I just had a look and actually this one is not needed 😅 So this could be removed from the entity.
> 
> Some other arguments I had in mind for having a single table are:
> 
> * Single consistent interface for querying all types of rewards
> * Ability to populate rewards in deposits with a single JOIN
>   
>   * If we, for example, had the `referrals` rewards also in this table, then we could have added a new column to the `deposits` entity to populate all related rewards with a single JOIN.
> 
> But I also get your point of having multiple tables. Because all above arguments could be achieved with multiple tables. And because the referrals are always in a separate view/table, we would need to some stitching anyways 🤔

@dohaki 
Ok, let's stick with the current approach for now since we have only the op rewards stored in this table for now anyway. It will be easy to switch to multiple tables approach if we decide to do that (it is only a table rename a a column drop).
But let's remove the columns that are not necessary (`rewardTokenPriceId `)

2023-11-22 14:45 UTC, dohaki commented on src/modules/rewards/entrypoints/http/controller.ts
> +  }
Yes, exactly

2023-11-22 14:46 UTC, dohaki commented on src/modules/rewards/entrypoints/http/dto.ts
> +export class GetRewardsQuery {
Yea, it will be used in the following PR. But I can also remove it from this one for now

2023-11-22 15:19 UTC, dohaki commented on .env.sample
> +OP_REBATES_REWARD_PROGRAM_END_TIMESTAMP_SEC=
Done https://github.com/across-protocol/scraper-api/pull/286/commits/e6ad735e295ae2d0e064d15ad7027a5edd1de158

2023-11-22 15:19 UTC, dohaki commented on migrations/1700494783985-Reward.ts
> +      `CREATE TABLE "reward" ("id" SERIAL NOT NULL, "depositPrimaryKey" integer NOT NULL, "recipient" character varying NOT NULL, "type" character varying NOT NULL, "metadata" jsonb NOT NULL, "amount
https://github.com/across-protocol/scraper-api/pull/286/commits/e6ad735e295ae2d0e064d15ad7027a5edd1de158

2023-11-22 15:19 UTC, dohaki commented on src/modules/configuration/index.ts
> +  },
https://github.com/across-protocol/scraper-api/pull/286/commits/e6ad735e295ae2d0e064d15ad7027a5edd1de158

2023-11-22 15:20 UTC, dohaki commented on src/modules/rewards/model/reward.entity.ts
> +@Unique("UK_reward_recipient_type_depositPk", ["recipient", "type", "depositPrimaryKey"])
The other way around. One reward entity of a certain type can have only one deposit per recipient

2023-11-22 15:20 UTC, dohaki commented on .env.sample
> +OP_REBATES_REWARD_PROGRAM_DISABLED=
https://github.com/across-protocol/scraper-api/pull/286/commits/e6ad735e295ae2d0e064d15ad7027a5edd1de158

2023-11-22 15:20 UTC, dohaki commented on src/modules/rewards/services/op-rebate-service.ts
> +    return DateTime.fromJSDate(deposit.depositDate).toSeconds() > start;
https://github.com/across-protocol/scraper-api/pull/286/commits/e6ad735e295ae2d0e064d15ad7027a5edd1de158

2023-11-22 15:20 UTC, dohaki commented on src/modules/rewards/services/op-rebate-service.ts
> +    const bridgeFeePctValues = calcPctValues(deposit.bridgeFeePct);
https://github.com/across-protocol/scraper-api/pull/286/commits/e6ad735e295ae2d0e064d15ad7027a5edd1de158

2023-11-22 15:20 UTC, dohaki commented on src/modules/rewards/services/op-rebate-service.ts
> +      this.appConfig.values.web3.rewardTokens["op-rebates"].cgId,
https://github.com/across-protocol/scraper-api/pull/286/commits/e6ad735e295ae2d0e064d15ad7027a5edd1de158

2023-11-22 15:21 UTC, dohaki commented on src/modules/rewards/services/op-rebate-service.ts
> +    }
https://github.com/across-protocol/scraper-api/pull/286/commits/e6ad735e295ae2d0e064d15ad7027a5edd1de158

2023-11-23 13:15 UTC, amateima approved these changes

2023-11-23 15:45 UTC, merged